apiVersion: v1
kind: Service
metadata:
  name: service-provider
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31001
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31002
      port: 8081
      targetPort: 8081
  selector:
    app: service-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-provider
  labels:
    app: service-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-provider
  template:
    metadata:
      name: service-provider
      labels:
        app: service-provider
    spec:
      restartPolicy: Always
      containers:
        - name: service-provider
          image: registry.cn-shanghai.aliyuncs.com/virtuex/service-provider:latest
          imagePullPolicy: Always
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m