apiVersion: v1
kind: Service
metadata:
  name: service-customer
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31003
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31004
      port: 8081
      targetPort: 8081
  selector:
    app: service-customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-customer
  labels:
    app: service-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-customer
  template:
    metadata:
      name: service-customer
      labels:
        app: service-customer
    spec:
      restartPolicy: Always
      containers:
        - name: service-customer
          image: registry.cn-beijing.aliyuncs.com/mydlq/service-customer:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m