apiVersion: v1
kind: Service
metadata:
  name: sleuth-service-provider
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31005
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31006
      port: 8081
      targetPort: 8081
  selector:
    app: sleuth-service-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleuth-service-provider
  labels:
    app: sleuth-service-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleuth-service-provider
  template:
    metadata:
      name: sleuth-service-provider
      labels:
        app: sleuth-service-provider
    spec:
      restartPolicy: Always
      containers:
        - name: sleuth-service-provider
          image: registry.cn-beijing.aliyuncs.com/mydlq/sleuth-service-provider:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m