apiVersion: v1
kind: Service
metadata:
  name: springcloud-kubernetes-config-demo
  namespace: mydlqcloud
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 30180
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 30181
      port: 8081
      targetPort: 8081
  selector:
    app: springcloud-kubernetes-config-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mydlqcloud
  name: springcloud-kubernetes-config-demo
  labels:
    app: springcloud-kubernetes-config-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcloud-kubernetes-config-demo
#      admin: enabled
  template:
    metadata:
      name: springcloud-kubernetes-config-demo
      labels:
        app: springcloud-kubernetes-config-demo
    spec:
      serviceAccountName: springcloud-kubernetes
      restartPolicy: Always
      containers:
        - name: springcloud-kubernetes-config-demo
          image: registry.cn-shanghai.aliyuncs.com/virtuex/springcloud-kubernetes-config-demo:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m